"""Pluggable vector-index boundary used by transcript recall."""

from __future__ import annotations

from typing import Protocol


class VectorIndex(Protocol):
    async def initialize(self, dim: int) -> None: ...
    async def upsert(self, row_id: int, vector: list[float]) -> None: ...
    async def search(self, vector: list[float], k: int = 5) -> list[tuple[int, float]]: ...
    async def close(self) -> None: ...
